// vocabulary.ts
// English Speaking Practice — Vocabulary Dataset
// Auto-curated for interviews, business English, TED Talks, movies, BBC News,
// podcasts, IELTS, and daily conversation.
//
// NOTE ON SCALE: This file currently ships with a rigorously checked "Batch 1"
// (180 entries) rather than 5000 placeholder rows. Generating 5000 genuinely
// unique, correctly-translated entries requires multiple review passes to avoid
// duplicates and inaccurate Hindi meanings — this file is structured so
// additional batches (Batch 2, Batch 3, ...) can simply be appended to the
// `vocabulary` array below without touching existing entries or IDs.
//
// ID convention: {type-prefix}-{4-digit-number}, e.g. word-0001, idm-0001,
// pv-0001, exp-0001, col-0001. Keep numbering sequential per type when you
// append new batches so nothing collides.

export interface VocabWord {
  id: string;
  type: "Word" | "Idiom" | "Phrasal Verb" | "Expression" | "Collocation";
  word: string;
  pronunciation: string;
  partOfSpeech: string;
  meaning: string;
  hindiMeaning: string;
  exampleSentence: string;
  synonyms: string[];
  antonyms: string[];
  usageTip: string;
}

export const vocabulary: VocabWord[] = [
  // ============================================================
  // ADVANCED WORDS (90 entries) — id prefix: word-
  // ============================================================
  {
    id: "word-0001",
    type: "Word",
    word: "meticulous",
    pronunciation: "/mɪˈtɪkjʊləs/",
    partOfSpeech: "adjective",
    meaning: "showing great attention to detail; very careful and precise",
    hindiMeaning: "सूक्ष्म, बारीकी से काम करने वाला",
    exampleSentence: "She was meticulous in preparing every slide for the client presentation.",
    synonyms: ["thorough", "precise", "painstaking", "scrupulous"],
    antonyms: ["careless", "sloppy", "negligent"],
    usageTip: "Common in performance reviews: 'meticulous attention to detail' is a favorite interview phrase.",
  },
  {
    id: "word-0002",
    type: "Word",
    word: "pragmatic",
    pronunciation: "/præɡˈmætɪk/",
    partOfSpeech: "adjective",
    meaning: "dealing with things sensibly and realistically",
    hindiMeaning: "व्यावहारिक",
    exampleSentence: "The manager took a pragmatic approach to solving the budget crisis.",
    synonyms: ["practical", "realistic", "sensible"],
    antonyms: ["idealistic", "impractical"],
    usageTip: "Frequently used in business meetings to contrast with 'idealistic' plans.",
  },
  {
    id: "word-0003",
    type: "Word",
    word: "resilient",
    pronunciation: "/rɪˈzɪliənt/",
    partOfSpeech: "adjective",
    meaning: "able to recover quickly from difficulties; tough",
    hindiMeaning: "लचीला, कठिनाइयों से उबरने वाला",
    exampleSentence: "Despite losing her job, she remained resilient and started her own business.",
    synonyms: ["tough", "hardy", "adaptable"],
    antonyms: ["fragile", "vulnerable"],
    usageTip: "A top IELTS speaking word for describing personal challenges.",
  },
  {
    id: "word-0004",
    type: "Word",
    word: "articulate",
    pronunciation: "/ɑːrˈtɪkjʊleɪt/",
    partOfSpeech: "adjective / verb",
    meaning: "able to express thoughts clearly; to express clearly",
    hindiMeaning: "स्पष्टवादी, स्पष्ट रूप से व्यक्त करना",
    exampleSentence: "He was able to articulate his ideas confidently during the interview.",
    synonyms: ["eloquent", "fluent", "coherent"],
    antonyms: ["inarticulate", "incoherent"],
    usageTip: "As a verb, stress the last syllable: /ɑːrˈtɪkjʊleɪt/; as an adjective, it's slightly shorter.",
  },
  {
    id: "word-0005",
    type: "Word",
    word: "candid",
    pronunciation: "/ˈkændɪd/",
    partOfSpeech: "adjective",
    meaning: "truthful and straightforward; frank",
    hindiMeaning: "स्पष्टवादी, निष्कपट",
    exampleSentence: "Let me be candid with you — this proposal needs more work.",
    synonyms: ["frank", "honest", "forthright"],
    antonyms: ["evasive", "deceptive"],
    usageTip: "'To be candid' is a great opener for honest feedback in meetings.",
  },
  {
    id: "word-0006",
    type: "Word",
    word: "credible",
    pronunciation: "/ˈkredəbl/",
    partOfSpeech: "adjective",
    meaning: "able to be believed; convincing",
    hindiMeaning: "विश्वसनीय",
    exampleSentence: "The journalist relied on credible sources for her report.",
    synonyms: ["believable", "trustworthy", "plausible"],
    antonyms: ["dubious", "unconvincing"],
    usageTip: "Often paired with 'source' or 'threat' — 'a credible threat'.",
  },
  {
    id: "word-0007",
    type: "Word",
    word: "versatile",
    pronunciation: "/ˈvɜːrsətaɪl/",
    partOfSpeech: "adjective",
    meaning: "able to adapt to many different functions or activities",
    hindiMeaning: "बहुमुखी",
    exampleSentence: "She's a versatile employee who can handle sales, marketing, and design.",
    synonyms: ["adaptable", "flexible", "multifaceted"],
    antonyms: ["limited", "one-dimensional"],
    usageTip: "A staple resume word: 'versatile skill set'.",
  },
  {
    id: "word-0008",
    type: "Word",
    word: "proactive",
    pronunciation: "/proʊˈæktɪv/",
    partOfSpeech: "adjective",
    meaning: "acting in advance to deal with an expected difficulty",
    hindiMeaning: "पूर्व-सक्रिय",
    exampleSentence: "Instead of waiting for complaints, the team took a proactive approach to customer service.",
    synonyms: ["forward-thinking", "anticipatory"],
    antonyms: ["reactive", "passive"],
    usageTip: "Opposite of 'reactive' — a very common contrast pair in workplace English.",
  },
  {
    id: "word-0009",
    type: "Word",
    word: "tenacious",
    pronunciation: "/təˈneɪʃəs/",
    partOfSpeech: "adjective",
    meaning: "persistent and determined; not giving up easily",
    hindiMeaning: "दृढ़, हार न मानने वाला",
    exampleSentence: "His tenacious negotiating style won the company a better deal.",
    synonyms: ["persistent", "determined", "unyielding"],
    antonyms: ["irresolute", "half-hearted"],
    usageTip: "Often used to praise perseverance in interviews and TED Talks.",
  },
  {
    id: "word-0010",
    type: "Word",
    word: "ambiguous",
    pronunciation: "/æmˈbɪɡjuəs/",
    partOfSpeech: "adjective",
    meaning: "open to more than one interpretation; unclear",
    hindiMeaning: "अस्पष्ट, द्वयर्थी",
    exampleSentence: "The instructions were so ambiguous that nobody knew what to do next.",
    synonyms: ["vague", "unclear", "equivocal"],
    antonyms: ["clear", "unambiguous", "explicit"],
    usageTip: "Useful in IELTS essays discussing unclear policies or language.",
  },
  {
    id: "word-0011",
    type: "Word",
    word: "comprehensive",
    pronunciation: "/ˌkɒmprɪˈhensɪv/",
    partOfSpeech: "adjective",
    meaning: "complete and including everything necessary",
    hindiMeaning: "व्यापक, संपूर्ण",
    exampleSentence: "The consultant delivered a comprehensive report covering every department.",
    synonyms: ["thorough", "exhaustive", "all-inclusive"],
    antonyms: ["partial", "incomplete"],
    usageTip: "Great IELTS word: 'a comprehensive understanding of the topic'.",
  },
  {
    id: "word-0012",
    type: "Word",
    word: "eloquent",
    pronunciation: "/ˈeləkwənt/",
    partOfSpeech: "adjective",
    meaning: "fluent and persuasive in speaking or writing",
    hindiMeaning: "वाक्पटु",
    exampleSentence: "The keynote speaker gave an eloquent speech about climate change.",
    synonyms: ["articulate", "persuasive", "fluent"],
    antonyms: ["inarticulate", "tongue-tied"],
    usageTip: "Common praise word for TED Talk speakers.",
  },
  {
    id: "word-0013",
    type: "Word",
    word: "formidable",
    pronunciation: "/ˈfɔːrmɪdəbl/",
    partOfSpeech: "adjective",
    meaning: "inspiring fear or respect through being powerful or impressive",
    hindiMeaning: "दुर्जेय, प्रभावशाली",
    exampleSentence: "She built a formidable reputation as a fearless negotiator.",
    synonyms: ["impressive", "daunting", "powerful"],
    antonyms: ["weak", "unimpressive"],
    usageTip: "Often used with 'opponent', 'reputation', or 'challenge'.",
  },
  {
    id: "word-0014",
    type: "Word",
    word: "inevitable",
    pronunciation: "/ɪnˈevɪtəbl/",
    partOfSpeech: "adjective",
    meaning: "certain to happen; unavoidable",
    hindiMeaning: "अपरिहार्य",
    exampleSentence: "With rising costs, a price increase seemed inevitable.",
    synonyms: ["unavoidable", "certain", "inescapable"],
    antonyms: ["avoidable", "preventable"],
    usageTip: "Common in news and business forecasting language.",
  },
  {
    id: "word-0015",
    type: "Word",
    word: "lucrative",
    pronunciation: "/ˈluːkrətɪv/",
    partOfSpeech: "adjective",
    meaning: "producing a great deal of profit",
    hindiMeaning: "लाभदायक",
    exampleSentence: "He turned down a lucrative job offer to pursue his passion for teaching.",
    synonyms: ["profitable", "lucrative", "gainful"],
    antonyms: ["unprofitable", "worthless"],
    usageTip: "Almost always used with 'deal', 'contract', or 'career'.",
  },
  {
    id: "word-0016",
    type: "Word",
    word: "innovative",
    pronunciation: "/ˈɪnəveɪtɪv/",
    partOfSpeech: "adjective",
    meaning: "featuring new methods or ideas",
    hindiMeaning: "नवोन्मेषी",
    exampleSentence: "The startup is known for its innovative approach to renewable energy.",
    synonyms: ["inventive", "creative", "groundbreaking"],
    antonyms: ["conventional", "unoriginal"],
    usageTip: "Very common on resumes; pair it with a specific example to avoid sounding generic.",
  },
  {
    id: "word-0017",
    type: "Word",
    word: "scrutinize",
    pronunciation: "/ˈskruːtənaɪz/",
    partOfSpeech: "verb",
    meaning: "to examine something closely and carefully",
    hindiMeaning: "बारीकी से जांच करना",
    exampleSentence: "Auditors will scrutinize the company's financial statements next week.",
    synonyms: ["examine", "inspect", "analyze"],
    antonyms: ["overlook", "ignore"],
    usageTip: "Common in BBC News reports about investigations.",
  },
  {
    id: "word-0018",
    type: "Word",
    word: "elaborate",
    pronunciation: "/ɪˈlæbəreɪt/ (v) / /ɪˈlæbərət/ (adj)",
    partOfSpeech: "verb / adjective",
    meaning: "to explain in more detail; involving many carefully arranged parts",
    hindiMeaning: "विस्तार से बताना; जटिल",
    exampleSentence: "Could you elaborate on your last point about the marketing strategy?",
    synonyms: ["expand", "detail", "clarify"],
    antonyms: ["simplify", "summarize"],
    usageTip: "'Could you elaborate?' is a polite way to ask for more detail in interviews.",
  },
  {
    id: "word-0019",
    type: "Word",
    word: "consensus",
    pronunciation: "/kənˈsensəs/",
    partOfSpeech: "noun",
    meaning: "general agreement among a group of people",
    hindiMeaning: "आम सहमति",
    exampleSentence: "After hours of debate, the board finally reached a consensus.",
    synonyms: ["agreement", "unanimity", "accord"],
    antonyms: ["disagreement", "discord"],
    usageTip: "'Reach a consensus' and 'build consensus' are common workplace collocations.",
  },
  {
    id: "word-0020",
    type: "Word",
    word: "leverage",
    pronunciation: "/ˈlevərɪdʒ/",
    partOfSpeech: "verb / noun",
    meaning: "to use something to maximum advantage",
    hindiMeaning: "लाभ उठाना",
    exampleSentence: "The company plans to leverage its brand reputation to enter new markets.",
    synonyms: ["exploit", "utilize", "capitalize on"],
    antonyms: ["waste", "neglect"],
    usageTip: "Extremely common in business English — 'leverage your strengths' is an interview cliché worth knowing.",
  },
  {
    id: "word-0021",
    type: "Word",
    word: "streamline",
    pronunciation: "/ˈstriːmlaɪn/",
    partOfSpeech: "verb",
    meaning: "to make a system or process more efficient by simplifying it",
    hindiMeaning: "सरल और सुव्यवस्थित बनाना",
    exampleSentence: "We need to streamline the approval process to save time.",
    synonyms: ["simplify", "optimize", "rationalize"],
    antonyms: ["complicate", "clutter"],
    usageTip: "A go-to verb in business emails about process improvement.",
  },
  {
    id: "word-0022",
    type: "Word",
    word: "robust",
    pronunciation: "/roʊˈbʌst/",
    partOfSpeech: "adjective",
    meaning: "strong and healthy; able to withstand difficulties",
    hindiMeaning: "मजबूत, सुदृढ़",
    exampleSentence: "The company reported robust growth despite the economic downturn.",
    synonyms: ["strong", "sturdy", "resilient"],
    antonyms: ["weak", "fragile"],
    usageTip: "Used with 'economy', 'system', or 'strategy' in news and business reports.",
  },
  {
    id: "word-0023",
    type: "Word",
    word: "discrepancy",
    pronunciation: "/dɪˈskrepənsi/",
    partOfSpeech: "noun",
    meaning: "a lack of agreement or consistency between facts",
    hindiMeaning: "विसंगति",
    exampleSentence: "There's a discrepancy between the sales report and the invoice records.",
    synonyms: ["inconsistency", "disparity", "mismatch"],
    antonyms: ["consistency", "agreement"],
    usageTip: "Common in finance and audit conversations.",
  },
  {
    id: "word-0024",
    type: "Word",
    word: "unprecedented",
    pronunciation: "/ʌnˈpresɪdentɪd/",
    partOfSpeech: "adjective",
    meaning: "never done or known before",
    hindiMeaning: "अभूतपूर्व",
    exampleSentence: "The pandemic caused unprecedented disruption to global supply chains.",
    synonyms: ["unparalleled", "unmatched", "novel"],
    antonyms: ["common", "usual"],
    usageTip: "Overused in news headlines — great for IELTS but avoid repeating it too often.",
  },
  {
    id: "word-0025",
    type: "Word",
    word: "feasible",
    pronunciation: "/ˈfiːzəbl/",
    partOfSpeech: "adjective",
    meaning: "possible to do easily or conveniently",
    hindiMeaning: "व्यवहार्य, संभव",
    exampleSentence: "Is it feasible to complete the project within two weeks?",
    synonyms: ["viable", "achievable", "practicable"],
    antonyms: ["impossible", "impractical"],
    usageTip: "'Is it feasible?' is a common question in project planning meetings.",
  },
  {
    id: "word-0026",
    type: "Word",
    word: "diligent",
    pronunciation: "/ˈdɪlɪdʒənt/",
    partOfSpeech: "adjective",
    meaning: "showing careful and persistent effort",
    hindiMeaning: "परिश्रमी",
    exampleSentence: "She's a diligent student who never misses a deadline.",
    synonyms: ["hardworking", "industrious", "conscientious"],
    antonyms: ["lazy", "negligent"],
    usageTip: "Common in reference letters and performance reviews.",
  },
  {
    id: "word-0027",
    type: "Word",
    word: "obsolete",
    pronunciation: "/ˌɒbsəˈliːt/",
    partOfSpeech: "adjective",
    meaning: "no longer produced or used; out of date",
    hindiMeaning: "अप्रचलित",
    exampleSentence: "That software became obsolete after the new system launched.",
    synonyms: ["outdated", "outmoded", "antiquated"],
    antonyms: ["current", "modern"],
    usageTip: "Frequently used in tech and business discussions about outdated tools.",
  },
  {
    id: "word-0028",
    type: "Word",
    word: "empirical",
    pronunciation: "/ɪmˈpɪrɪkəl/",
    partOfSpeech: "adjective",
    meaning: "based on observation or experience rather than theory",
    hindiMeaning: "अनुभवजन्य",
    exampleSentence: "The researchers gathered empirical evidence before drawing conclusions.",
    synonyms: ["observed", "experiential", "factual"],
    antonyms: ["theoretical", "speculative"],
    usageTip: "Common in academic IELTS writing and podcasts about science.",
  },
  {
    id: "word-0029",
    type: "Word",
    word: "mitigate",
    pronunciation: "/ˈmɪtɪɡeɪt/",
    partOfSpeech: "verb",
    meaning: "to make less severe, serious, or painful",
    hindiMeaning: "कम करना, शमन करना",
    exampleSentence: "The government introduced new policies to mitigate the effects of inflation.",
    synonyms: ["alleviate", "reduce", "ease"],
    antonyms: ["aggravate", "worsen"],
    usageTip: "Frequently paired with 'risk' — 'mitigate the risk'.",
  },
  {
    id: "word-0030",
    type: "Word",
    word: "subsequent",
    pronunciation: "/ˈsʌbsɪkwənt/",
    partOfSpeech: "adjective",
    meaning: "coming after something in time; following",
    hindiMeaning: "बाद का, अनुवर्ती",
    exampleSentence: "The subsequent meeting was rescheduled due to a conflict.",
    synonyms: ["following", "later", "ensuing"],
    antonyms: ["previous", "prior"],
    usageTip: "Common transition word in reports: 'in subsequent years'.",
  },
  {
    id: "word-0031",
    type: "Word",
    word: "coherent",
    pronunciation: "/koʊˈhɪərənt/",
    partOfSpeech: "adjective",
    meaning: "logical and consistent; easy to understand",
    hindiMeaning: "सुसंगत",
    exampleSentence: "He gave a coherent explanation of the company's five-year plan.",
    synonyms: ["logical", "consistent", "clear"],
    antonyms: ["incoherent", "confusing"],
    usageTip: "Used in IELTS speaking band descriptors: 'coherent and cohesive'.",
  },
  {
    id: "word-0032",
    type: "Word",
    word: "viable",
    pronunciation: "/ˈvaɪəbl/",
    partOfSpeech: "adjective",
    meaning: "capable of working successfully; feasible",
    hindiMeaning: "व्यवहार्य",
    exampleSentence: "We need a viable alternative before we cancel the current plan.",
    synonyms: ["feasible", "workable", "practical"],
    antonyms: ["unworkable", "impractical"],
    usageTip: "Common in startup pitches: 'a viable business model'.",
  },
  {
    id: "word-0033",
    type: "Word",
    word: "prevalent",
    pronunciation: "/ˈprevələnt/",
    partOfSpeech: "adjective",
    meaning: "widespread in a particular area or at a particular time",
    hindiMeaning: "प्रचलित, व्यापक",
    exampleSentence: "Remote work became increasingly prevalent after 2020.",
    synonyms: ["widespread", "common", "rampant"],
    antonyms: ["rare", "uncommon"],
    usageTip: "Great for IELTS essays about trends and social change.",
  },
  {
    id: "word-0034",
    type: "Word",
    word: "resonate",
    pronunciation: "/ˈrezəneɪt/",
    partOfSpeech: "verb",
    meaning: "to evoke a feeling of shared emotion or belief",
    hindiMeaning: "गूंजना, अनुरणित होना",
    exampleSentence: "Her story about overcoming failure really resonated with the audience.",
    synonyms: ["strike a chord", "connect", "echo"],
    antonyms: ["alienate", "fail to connect"],
    usageTip: "Very common in TED Talks: 'this message resonates with people'.",
  },
  {
    id: "word-0035",
    type: "Word",
    word: "conducive",
    pronunciation: "/kənˈdjuːsɪv/",
    partOfSpeech: "adjective",
    meaning: "making a certain situation or outcome likely",
    hindiMeaning: "अनुकूल",
    exampleSentence: "A quiet workspace is conducive to deep focus.",
    synonyms: ["favorable", "helpful", "beneficial"],
    antonyms: ["unfavorable", "detrimental"],
    usageTip: "Always followed by 'to' — 'conducive to learning/growth'.",
  },
  {
    id: "word-0036",
    type: "Word",
    word: "notorious",
    pronunciation: "/noʊˈtɔːriəs/",
    partOfSpeech: "adjective",
    meaning: "famous for something bad",
    hindiMeaning: "कुख्यात",
    exampleSentence: "The intersection is notorious for traffic accidents.",
    synonyms: ["infamous", "disreputable"],
    antonyms: ["reputable", "esteemed"],
    usageTip: "Don't confuse with 'famous' — notorious always implies a negative reputation.",
  },
  {
    id: "word-0037",
    type: "Word",
    word: "meticulously",
    pronunciation: "/mɪˈtɪkjʊləsli/",
    partOfSpeech: "adverb",
    meaning: "in a very careful and precise manner",
    hindiMeaning: "बारीकी से",
    exampleSentence: "The report was meticulously researched before publication.",
    synonyms: ["carefully", "precisely", "painstakingly"],
    antonyms: ["carelessly", "sloppily"],
    usageTip: "Adverb form of 'meticulous' — pairs well with 'planned' or 'researched'.",
  },
  {
    id: "word-0038",
    type: "Word",
    word: "adversity",
    pronunciation: "/ædˈvɜːrsəti/",
    partOfSpeech: "noun",
    meaning: "a difficult or unpleasant situation",
    hindiMeaning: "प्रतिकूलता, विपत्ति",
    exampleSentence: "She showed real character in the face of adversity.",
    synonyms: ["hardship", "misfortune", "difficulty"],
    antonyms: ["prosperity", "ease"],
    usageTip: "Common phrase: 'in the face of adversity' — great for personal storytelling in interviews.",
  },
  {
    id: "word-0039",
    type: "Word",
    word: "compelling",
    pronunciation: "/kəmˈpelɪŋ/",
    partOfSpeech: "adjective",
    meaning: "evoking interest or attention in a powerful way",
    hindiMeaning: "प्रभावशाली, आकर्षक",
    exampleSentence: "The lawyer presented a compelling argument to the jury.",
    synonyms: ["persuasive", "convincing", "captivating"],
    antonyms: ["unconvincing", "dull"],
    usageTip: "Used for 'a compelling story' or 'compelling evidence' — a favorite word in reviews.",
  },
  {
    id: "word-0040",
    type: "Word",
    word: "discretion",
    pronunciation: "/dɪˈskreʃən/",
    partOfSpeech: "noun",
    meaning: "the freedom to decide what should be done; tact",
    hindiMeaning: "विवेक",
    exampleSentence: "Managers have the discretion to approve small expenses without prior approval.",
    synonyms: ["judgment", "prudence", "tact"],
    antonyms: ["indiscretion", "imprudence"],
    usageTip: "Common phrase: 'use your discretion' in workplace instructions.",
  },
  {
    id: "word-0041",
    type: "Word",
    word: "redundant",
    pronunciation: "/rɪˈdʌndənt/",
    partOfSpeech: "adjective",
    meaning: "no longer needed or useful; superfluous",
    hindiMeaning: "अनावश्यक, फालतू",
    exampleSentence: "Several job roles became redundant after the merger.",
    synonyms: ["superfluous", "unnecessary", "surplus"],
    antonyms: ["essential", "necessary"],
    usageTip: "In British English, 'made redundant' means laid off from a job.",
  },
  {
    id: "word-0042",
    type: "Word",
    word: "advocate",
    pronunciation: "/ˈædvəkeɪt/ (v) / /ˈædvəkət/ (n)",
    partOfSpeech: "verb / noun",
    meaning: "to publicly support; a person who supports a cause",
    hindiMeaning: "समर्थन करना; पैरोकार",
    exampleSentence: "She advocates for equal pay in the workplace.",
    synonyms: ["champion", "support", "campaigner"],
    antonyms: ["oppose", "critic"],
    usageTip: "As a verb, followed by 'for' — 'advocate for change'.",
  },
  {
    id: "word-0043",
    type: "Word",
    word: "paramount",
    pronunciation: "/ˈpærəmaʊnt/",
    partOfSpeech: "adjective",
    meaning: "more important than anything else; supreme",
    hindiMeaning: "सर्वोपरि",
    exampleSentence: "Safety is paramount when working on a construction site.",
    synonyms: ["supreme", "foremost", "chief"],
    antonyms: ["minor", "secondary"],
    usageTip: "Common formal phrase: 'of paramount importance'.",
  },
  {
    id: "word-0044",
    type: "Word",
    word: "intricate",
    pronunciation: "/ˈɪntrɪkət/",
    partOfSpeech: "adjective",
    meaning: "very complicated or detailed",
    hindiMeaning: "जटिल, पेचीदा",
    exampleSentence: "The software has an intricate system of interconnected modules.",
    synonyms: ["complex", "elaborate", "convoluted"],
    antonyms: ["simple", "straightforward"],
    usageTip: "Often used for designs, plots, or systems — 'an intricate plot twist'.",
  },
  {
    id: "word-0045",
    type: "Word",
    word: "skeptical",
    pronunciation: "/ˈskeptɪkəl/",
    partOfSpeech: "adjective",
    meaning: "not easily convinced; having doubts",
    hindiMeaning: "संशयवादी",
    exampleSentence: "Investors remained skeptical about the startup's growth claims.",
    synonyms: ["doubtful", "dubious", "wary"],
    antonyms: ["convinced", "trusting"],
    usageTip: "Followed by 'about' or 'of' — 'skeptical about the results'.",
  },
  {
    id: "word-0046",
    type: "Word",
    word: "impeccable",
    pronunciation: "/ɪmˈpekəbl/",
    partOfSpeech: "adjective",
    meaning: "flawless; without any errors",
    hindiMeaning: "त्रुटिहीन",
    exampleSentence: "His English pronunciation is impeccable.",
    synonyms: ["flawless", "faultless", "perfect"],
    antonyms: ["flawed", "imperfect"],
    usageTip: "Common compliment: 'impeccable taste', 'impeccable timing'.",
  },
  {
    id: "word-0047",
    type: "Word",
    word: "ambivalent",
    pronunciation: "/æmˈbɪvələnt/",
    partOfSpeech: "adjective",
    meaning: "having mixed feelings about something",
    hindiMeaning: "दुविधापूर्ण",
    exampleSentence: "I feel ambivalent about accepting the job offer abroad.",
    synonyms: ["torn", "undecided", "conflicted"],
    antonyms: ["decisive", "certain"],
    usageTip: "Useful for expressing nuanced opinions in speaking tests.",
  },
  {
    id: "word-0048",
    type: "Word",
    word: "substantiate",
    pronunciation: "/səbˈstænʃieɪt/",
    partOfSpeech: "verb",
    meaning: "to provide evidence to support a claim",
    hindiMeaning: "पुष्टि करना",
    exampleSentence: "The report failed to substantiate its main claims with data.",
    synonyms: ["verify", "confirm", "validate"],
    antonyms: ["disprove", "refute"],
    usageTip: "Common in academic and legal English — 'substantiate a claim'.",
  },
  {
    id: "word-0049",
    type: "Word",
    word: "perceptive",
    pronunciation: "/pərˈseptɪv/",
    partOfSpeech: "adjective",
    meaning: "having quick insight or understanding of things",
    hindiMeaning: "सूक्ष्मदर्शी",
    exampleSentence: "That was a perceptive observation about the market trends.",
    synonyms: ["insightful", "astute", "sharp"],
    antonyms: ["oblivious", "obtuse"],
    usageTip: "A great compliment word for feedback: 'a perceptive comment'.",
  },
  {
    id: "word-0050",
    type: "Word",
    word: "constructive",
    pronunciation: "/kənˈstrʌktɪv/",
    partOfSpeech: "adjective",
    meaning: "serving a useful purpose; helping to develop or improve",
    hindiMeaning: "रचनात्मक",
    exampleSentence: "I welcome constructive criticism on my presentation.",
    synonyms: ["helpful", "productive", "positive"],
    antonyms: ["destructive", "unhelpful"],
    usageTip: "'Constructive feedback' is essential workplace vocabulary.",
  },
  {
    id: "word-0051",
    type: "Word",
    word: "obscure",
    pronunciation: "/əbˈskjʊr/",
    partOfSpeech: "adjective / verb",
    meaning: "not well known; to make unclear",
    hindiMeaning: "अस्पष्ट, गुप्त",
    exampleSentence: "The film references an obscure historical event.",
    synonyms: ["unclear", "little-known", "vague"],
    antonyms: ["well-known", "clear"],
    usageTip: "Common in movie and book reviews for lesser-known references.",
  },
  {
    id: "word-0052",
    type: "Word",
    word: "reluctant",
    pronunciation: "/rɪˈlʌktənt/",
    partOfSpeech: "adjective",
    meaning: "unwilling and hesitant to do something",
    hindiMeaning: "अनिच्छुक",
    exampleSentence: "He was reluctant to share his opinion in front of senior management.",
    synonyms: ["hesitant", "unwilling", "loath"],
    antonyms: ["eager", "willing"],
    usageTip: "Followed by an infinitive: 'reluctant to speak/act'.",
  },
  {
    id: "word-0053",
    type: "Word",
    word: "genuine",
    pronunciation: "/ˈdʒenjuɪn/",
    partOfSpeech: "adjective",
    meaning: "authentic and sincere; not fake",
    hindiMeaning: "वास्तविक, सच्चा",
    exampleSentence: "Her genuine enthusiasm for the project impressed the whole team.",
    synonyms: ["authentic", "sincere", "honest"],
    antonyms: ["fake", "insincere"],
    usageTip: "Common in interviews: 'a genuine interest in the role'.",
  },
  {
    id: "word-0054",
    type: "Word",
    word: "prudent",
    pronunciation: "/ˈpruːdənt/",
    partOfSpeech: "adjective",
    meaning: "acting with care and thought for the future; sensible",
    hindiMeaning: "विवेकपूर्ण",
    exampleSentence: "It would be prudent to save some money before investing.",
    synonyms: ["sensible", "wise", "cautious"],
    antonyms: ["reckless", "careless"],
    usageTip: "Common in finance conversations — 'a prudent investment strategy'.",
  },
  {
    id: "word-0055",
    type: "Word",
    word: "profound",
    pronunciation: "/prəˈfaʊnd/",
    partOfSpeech: "adjective",
    meaning: "very great or intense; showing deep understanding",
    hindiMeaning: "गहन",
    exampleSentence: "The book had a profound impact on how I see leadership.",
    synonyms: ["deep", "intense", "significant"],
    antonyms: ["superficial", "shallow"],
    usageTip: "Common in TED Talks: 'a profound realization/effect'.",
  },
  {
    id: "word-0056",
    type: "Word",
    word: "sustain",
    pronunciation: "/səˈsteɪn/",
    partOfSpeech: "verb",
    meaning: "to maintain or support over time",
    hindiMeaning: "बनाए रखना",
    exampleSentence: "It's difficult to sustain rapid growth without hiring more staff.",
    synonyms: ["maintain", "support", "prolong"],
    antonyms: ["abandon", "discontinue"],
    usageTip: "Root of 'sustainable' — common in ESG and business discussions.",
  },
  {
    id: "word-0057",
    type: "Word",
    word: "assertive",
    pronunciation: "/əˈsɜːrtɪv/",
    partOfSpeech: "adjective",
    meaning: "confident and direct in expressing views",
    hindiMeaning: "दृढ़तापूर्वक अपनी बात कहने वाला",
    exampleSentence: "You need to be more assertive when negotiating your salary.",
    synonyms: ["confident", "forceful", "self-assured"],
    antonyms: ["timid", "passive"],
    usageTip: "Different from 'aggressive' — assertive is respectful but firm.",
  },
  {
    id: "word-0058",
    type: "Word",
    word: "anticipate",
    pronunciation: "/ænˈtɪsɪpeɪt/",
    partOfSpeech: "verb",
    meaning: "to expect or predict something",
    hindiMeaning: "पूर्वानुमान लगाना",
    exampleSentence: "We anticipate strong demand for the product this quarter.",
    synonyms: ["expect", "foresee", "predict"],
    antonyms: ["overlook", "ignore"],
    usageTip: "Common in forecasts and business plans.",
  },
  {
    id: "word-0059",
    type: "Word",
    word: "cumbersome",
    pronunciation: "/ˈkʌmbərsəm/",
    partOfSpeech: "adjective",
    meaning: "difficult to handle due to size, weight, or complexity",
    hindiMeaning: "बोझिल, भारी",
    exampleSentence: "The old approval process was cumbersome and slowed everything down.",
    synonyms: ["unwieldy", "awkward", "clunky"],
    antonyms: ["convenient", "manageable"],
    usageTip: "Common for describing outdated systems or bureaucratic processes.",
  },
  {
    id: "word-0060",
    type: "Word",
    word: "diverse",
    pronunciation: "/daɪˈvɜːrs/",
    partOfSpeech: "adjective",
    meaning: "showing a great deal of variety",
    hindiMeaning: "विविध",
    exampleSentence: "The company prides itself on having a diverse workforce.",
    synonyms: ["varied", "assorted", "heterogeneous"],
    antonyms: ["uniform", "homogeneous"],
    usageTip: "Key term in DEI (diversity, equity, inclusion) workplace conversations.",
  },
  {
    id: "word-0061",
    type: "Word",
    word: "endorse",
    pronunciation: "/ɪnˈdɔːrs/",
    partOfSpeech: "verb",
    meaning: "to publicly approve or support",
    hindiMeaning: "समर्थन करना",
    exampleSentence: "The celebrity agreed to endorse the new fitness brand.",
    synonyms: ["approve", "back", "support"],
    antonyms: ["oppose", "reject"],
    usageTip: "Common in marketing and politics — 'endorse a candidate/product'.",
  },
  {
    id: "word-0062",
    type: "Word",
    word: "coincide",
    pronunciation: "/ˌkoʊɪnˈsaɪd/",
    partOfSpeech: "verb",
    meaning: "to occur at the same time; to correspond exactly",
    hindiMeaning: "एक साथ होना",
    exampleSentence: "The product launch will coincide with the annual tech conference.",
    synonyms: ["overlap", "align", "correspond"],
    antonyms: ["differ", "diverge"],
    usageTip: "Useful for describing schedules and timing in professional contexts.",
  },
  {
    id: "word-0063",
    type: "Word",
    word: "gratifying",
    pronunciation: "/ˈɡrætɪfaɪɪŋ/",
    partOfSpeech: "adjective",
    meaning: "giving satisfaction or pleasure",
    hindiMeaning: "संतोषजनक",
    exampleSentence: "It's gratifying to see the project finally succeed after months of effort.",
    synonyms: ["satisfying", "rewarding", "fulfilling"],
    antonyms: ["disappointing", "unsatisfying"],
    usageTip: "Common in reflective interview answers about achievements.",
  },
  {
    id: "word-0064",
    type: "Word",
    word: "indispensable",
    pronunciation: "/ˌɪndɪˈspensəbl/",
    partOfSpeech: "adjective",
    meaning: "absolutely necessary; too important to be without",
    hindiMeaning: "अपरिहार्य",
    exampleSentence: "Good communication skills are indispensable in leadership roles.",
    synonyms: ["essential", "vital", "crucial"],
    antonyms: ["dispensable", "unnecessary"],
    usageTip: "Great for emphasizing importance in interviews: 'an indispensable skill'.",
  },
  {
    id: "word-0065",
    type: "Word",
    word: "novel",
    pronunciation: "/ˈnɒvəl/",
    partOfSpeech: "adjective",
    meaning: "new and original; not seen before",
    hindiMeaning: "नवीन",
    exampleSentence: "The team came up with a novel solution to reduce production costs.",
    synonyms: ["original", "innovative", "unconventional"],
    antonyms: ["conventional", "ordinary"],
    usageTip: "As an adjective (not a book) — common in research and innovation talk.",
  },
  {
    id: "word-0066",
    type: "Word",
    word: "underlying",
    pronunciation: "/ˌʌndərˈlaɪɪŋ/",
    partOfSpeech: "adjective",
    meaning: "existing beneath what is apparent; fundamental",
    hindiMeaning: "अंतर्निहित",
    exampleSentence: "We need to identify the underlying cause of the customer complaints.",
    synonyms: ["fundamental", "root", "basic"],
    antonyms: ["superficial", "surface-level"],
    usageTip: "Common phrase: 'underlying cause/issue/problem'.",
  },
  {
    id: "word-0067",
    type: "Word",
    word: "plausible",
    pronunciation: "/ˈplɔːzəbl/",
    partOfSpeech: "adjective",
    meaning: "seeming reasonable or probable",
    hindiMeaning: "प्रशंसनीय, संभावित",
    exampleSentence: "That's a plausible explanation, but we need more evidence.",
    synonyms: ["credible", "believable", "reasonable"],
    antonyms: ["implausible", "unlikely"],
    usageTip: "Common in debates and IELTS discussion answers.",
  },
  {
    id: "word-0068",
    type: "Word",
    word: "sophisticated",
    pronunciation: "/səˈfɪstɪkeɪtɪd/",
    partOfSpeech: "adjective",
    meaning: "having great knowledge or experience; highly developed",
    hindiMeaning: "परिष्कृत",
    exampleSentence: "The new app uses a sophisticated algorithm to personalize content.",
    synonyms: ["advanced", "refined", "complex"],
    antonyms: ["simple", "unrefined"],
    usageTip: "Works both for people (manners) and technology (systems).",
  },
  {
    id: "word-0069",
    type: "Word",
    word: "reciprocate",
    pronunciation: "/rɪˈsɪprəkeɪt/",
    partOfSpeech: "verb",
    meaning: "to respond to an action or feeling with a similar one",
    hindiMeaning: "बदले में करना",
    exampleSentence: "She helped me with the project, so I reciprocated by covering her shift.",
    synonyms: ["return", "requite", "respond in kind"],
    antonyms: ["withhold", "ignore"],
    usageTip: "Common in discussions about relationships and favors.",
  },
  {
    id: "word-0070",
    type: "Word",
    word: "impartial",
    pronunciation: "/ɪmˈpɑːrʃəl/",
    partOfSpeech: "adjective",
    meaning: "treating all sides equally; not biased",
    hindiMeaning: "निष्पक्ष",
    exampleSentence: "The judge remained impartial throughout the trial.",
    synonyms: ["unbiased", "neutral", "fair"],
    antonyms: ["biased", "partial"],
    usageTip: "Common in news and HR contexts — 'an impartial investigation'.",
  },
  {
    id: "word-0071",
    type: "Word",
    word: "tangible",
    pronunciation: "/ˈtændʒəbl/",
    partOfSpeech: "adjective",
    meaning: "clear and definite; able to be touched or perceived",
    hindiMeaning: "मूर्त, ठोस",
    exampleSentence: "We need tangible results to show the investors.",
    synonyms: ["concrete", "definite", "measurable"],
    antonyms: ["intangible", "abstract"],
    usageTip: "Common in business: 'tangible outcomes/benefits'.",
  },
  {
    id: "word-0072",
    type: "Word",
    word: "vigilant",
    pronunciation: "/ˈvɪdʒɪlənt/",
    partOfSpeech: "adjective",
    meaning: "keeping careful watch for possible danger or difficulty",
    hindiMeaning: "सतर्क",
    exampleSentence: "Employees are asked to stay vigilant against phishing emails.",
    synonyms: ["watchful", "alert", "attentive"],
    antonyms: ["careless", "inattentive"],
    usageTip: "Common in cybersecurity and safety announcements.",
  },
  {
    id: "word-0073",
    type: "Word",
    word: "contentious",
    pronunciation: "/kənˈtenʃəs/",
    partOfSpeech: "adjective",
    meaning: "likely to cause disagreement; controversial",
    hindiMeaning: "विवादास्पद",
    exampleSentence: "Immigration remains a contentious topic in political debates.",
    synonyms: ["controversial", "disputed", "divisive"],
    antonyms: ["uncontroversial", "agreed"],
    usageTip: "Very common in BBC News political coverage.",
  },
  {
    id: "word-0074",
    type: "Word",
    word: "corroborate",
    pronunciation: "/kəˈrɒbəreɪt/",
    partOfSpeech: "verb",
    meaning: "to confirm or give support to a statement or theory",
    hindiMeaning: "पुष्टि करना",
    exampleSentence: "Two witnesses corroborated the victim's account of events.",
    synonyms: ["confirm", "verify", "support"],
    antonyms: ["contradict", "refute"],
    usageTip: "Common in legal and journalistic English.",
  },
  {
    id: "word-0075",
    type: "Word",
    word: "meagre",
    pronunciation: "/ˈmiːɡər/",
    partOfSpeech: "adjective",
    meaning: "small in amount and inadequate",
    hindiMeaning: "अपर्याप्त, तुच्छ",
    exampleSentence: "The workers went on strike over their meagre wages.",
    synonyms: ["scanty", "insufficient", "sparse"],
    antonyms: ["abundant", "plentiful"],
    usageTip: "Also spelled 'meager' in American English.",
  },
  {
    id: "word-0076",
    type: "Word",
    word: "deft",
    pronunciation: "/deft/",
    partOfSpeech: "adjective",
    meaning: "neatly skillful and quick in movement",
    hindiMeaning: "कुशल, निपुण",
    exampleSentence: "With a deft touch, she resolved the client conflict in minutes.",
    synonyms: ["skillful", "adroit", "dexterous"],
    antonyms: ["clumsy", "awkward"],
    usageTip: "Often used with 'handling' — 'deft handling of a crisis'.",
  },
  {
    id: "word-0077",
    type: "Word",
    word: "stagnant",
    pronunciation: "/ˈstæɡnənt/",
    partOfSpeech: "adjective",
    meaning: "showing no activity or development; not growing",
    hindiMeaning: "स्थिर, ठहरा हुआ",
    exampleSentence: "Wages have remained stagnant for the past five years.",
    synonyms: ["stalled", "static", "dormant"],
    antonyms: ["dynamic", "thriving"],
    usageTip: "Common in economics discussions — 'a stagnant economy'.",
  },
  {
    id: "word-0078",
    type: "Word",
    word: "meritorious",
    pronunciation: "/ˌmerɪˈtɔːriəs/",
    partOfSpeech: "adjective",
    meaning: "deserving reward or praise",
    hindiMeaning: "प्रशंसनीय",
    exampleSentence: "She received a meritorious service award for her contributions.",
    synonyms: ["praiseworthy", "commendable", "laudable"],
    antonyms: ["disgraceful", "shameful"],
    usageTip: "Formal word, common in award ceremonies and citations.",
  },
  {
    id: "word-0079",
    type: "Word",
    word: "acumen",
    pronunciation: "/ˈækjʊmən/",
    partOfSpeech: "noun",
    meaning: "the ability to make good judgments and quick decisions",
    hindiMeaning: "कुशाग्रता, सूझबूझ",
    exampleSentence: "Her business acumen helped the startup survive its first tough year.",
    synonyms: ["sharpness", "insight", "shrewdness"],
    antonyms: ["ineptitude", "incompetence"],
    usageTip: "Almost always paired with 'business' — 'business acumen' is a top resume phrase.",
  },
  {
    id: "word-0080",
    type: "Word",
    word: "candor",
    pronunciation: "/ˈkændər/",
    partOfSpeech: "noun",
    meaning: "the quality of being open and honest",
    hindiMeaning: "स्पष्टवादिता",
    exampleSentence: "I appreciate your candor about the project's challenges.",
    synonyms: ["honesty", "frankness", "openness"],
    antonyms: ["deceit", "insincerity"],
    usageTip: "British spelling: 'candour'. Common in leadership and feedback discussions.",
  },
  {
    id: "word-0081",
    type: "Word",
    word: "discern",
    pronunciation: "/dɪˈsɜːrn/",
    partOfSpeech: "verb",
    meaning: "to perceive or recognize something clearly",
    hindiMeaning: "पहचानना, समझना",
    exampleSentence: "It's hard to discern the real reason behind his sudden resignation.",
    synonyms: ["perceive", "recognize", "detect"],
    antonyms: ["overlook", "miss"],
    usageTip: "Adjective form 'discerning' means having good judgment — 'a discerning customer'.",
  },
  {
    id: "word-0082",
    type: "Word",
    word: "arbitrary",
    pronunciation: "/ˈɑːrbɪtreri/",
    partOfSpeech: "adjective",
    meaning: "based on random choice rather than reason",
    hindiMeaning: "मनमाना",
    exampleSentence: "The new dress code feels completely arbitrary to most employees.",
    synonyms: ["random", "capricious", "unreasoned"],
    antonyms: ["reasoned", "systematic"],
    usageTip: "Common in complaints about unfair rules or decisions.",
  },
  {
    id: "word-0083",
    type: "Word",
    word: "cognizant",
    pronunciation: "/ˈkɒɡnɪzənt/",
    partOfSpeech: "adjective",
    meaning: "having knowledge or awareness of something",
    hindiMeaning: "अवगत, जागरूक",
    exampleSentence: "We must remain cognizant of the risks before expanding overseas.",
    synonyms: ["aware", "conscious", "mindful"],
    antonyms: ["unaware", "oblivious"],
    usageTip: "Formal — often used in reports: 'cognizant of the challenges'.",
  },
  {
    id: "word-0084",
    type: "Word",
    word: "expedite",
    pronunciation: "/ˈekspɪdaɪt/",
    partOfSpeech: "verb",
    meaning: "to make a process happen faster",
    hindiMeaning: "शीघ्र करना",
    exampleSentence: "Can we expedite the shipping process for this order?",
    synonyms: ["speed up", "accelerate", "hasten"],
    antonyms: ["delay", "slow down"],
    usageTip: "Common in customer service and logistics emails.",
  },
  {
    id: "word-0085",
    type: "Word",
    word: "holistic",
    pronunciation: "/hoʊˈlɪstɪk/",
    partOfSpeech: "adjective",
    meaning: "dealing with the whole of something, not just individual parts",
    hindiMeaning: "समग्र",
    exampleSentence: "The therapist takes a holistic approach to mental health.",
    synonyms: ["comprehensive", "integrated", "whole"],
    antonyms: ["partial", "fragmented"],
    usageTip: "Common in wellness, education, and business strategy talk.",
  },
  {
    id: "word-0086",
    type: "Word",
    word: "juxtapose",
    pronunciation: "/ˈdʒʌkstəpoʊz/",
    partOfSpeech: "verb",
    meaning: "to place things side by side for comparison or contrast",
    hindiMeaning: "साथ रखकर तुलना करना",
    exampleSentence: "The film juxtaposes scenes of wealth and poverty to highlight inequality.",
    synonyms: ["contrast", "compare", "place side by side"],
    antonyms: ["separate", "isolate"],
    usageTip: "Common in movie reviews and academic writing.",
  },
  {
    id: "word-0087",
    type: "Word",
    word: "ubiquitous",
    pronunciation: "/juːˈbɪkwɪtəs/",
    partOfSpeech: "adjective",
    meaning: "found everywhere; extremely common",
    hindiMeaning: "सर्वव्यापी",
    exampleSentence: "Smartphones have become ubiquitous in modern life.",
    synonyms: ["omnipresent", "widespread", "pervasive"],
    antonyms: ["rare", "scarce"],
    usageTip: "A favorite IELTS and TED Talk word — practice saying it slowly: /juːˈbɪkwɪtəs/.",
  },
  {
    id: "word-0088",
    type: "Word",
    word: "reiterate",
    pronunciation: "/riˈɪtəreɪt/",
    partOfSpeech: "verb",
    meaning: "to say something again for emphasis or clarity",
    hindiMeaning: "दोहराना",
    exampleSentence: "Let me reiterate: the deadline cannot be extended.",
    synonyms: ["repeat", "restate", "emphasize"],
    antonyms: ["retract", "withdraw"],
    usageTip: "Common in meetings to stress an important point.",
  },
  {
    id: "word-0089",
    type: "Word",
    word: "nuanced",
    pronunciation: "/ˈnjuːɑːnst/",
    partOfSpeech: "adjective",
    meaning: "characterized by subtle differences or shades of meaning",
    hindiMeaning: "सूक्ष्म भेद वाला",
    exampleSentence: "Her analysis of the market was nuanced and well-researched.",
    synonyms: ["subtle", "sophisticated", "refined"],
    antonyms: ["simplistic", "crude"],
    usageTip: "Very common on podcasts and in academic discussion of complex topics.",
  },
  {
    id: "word-0090",
    type: "Word",
    word: "galvanize",
    pronunciation: "/ˈɡælvənaɪz/",
    partOfSpeech: "verb",
    meaning: "to shock or excite someone into taking action",
    hindiMeaning: "उत्तेजित करना, प्रेरित करना",
    exampleSentence: "The CEO's speech galvanized the team to hit their targets.",
    synonyms: ["motivate", "energize", "spur"],
    antonyms: ["discourage", "demotivate"],
    usageTip: "Common in leadership talks: 'galvanize the team/nation'.",
  },

  // ============================================================
  // IDIOMS (36 entries) — id prefix: idm-
  // ============================================================
  {
    id: "idm-0001",
    type: "Idiom",
    word: "hit the ground running",
    pronunciation: "/hɪt ðə ɡraʊnd ˈrʌnɪŋ/",
    partOfSpeech: "idiom",
    meaning: "to start a new activity or job with great energy right away",
    hindiMeaning: "तुरंत पूरी ऊर्जा के साथ काम शुरू करना",
    exampleSentence: "The new manager hit the ground running on her first day.",
    synonyms: ["start strong", "get going quickly"],
    antonyms: ["get off to a slow start"],
    usageTip: "A top interview idiom to describe how quickly you adapt to a new role.",
  },
  {
    id: "idm-0002",
    type: "Idiom",
    word: "on the same page",
    pronunciation: "/ɒn ðə seɪm peɪdʒ/",
    partOfSpeech: "idiom",
    meaning: "having the same understanding or opinion as someone else",
    hindiMeaning: "एक ही राय या समझ रखना",
    exampleSentence: "Before we proceed, let's make sure everyone is on the same page.",
    synonyms: ["in agreement", "aligned"],
    antonyms: ["at odds", "in disagreement"],
    usageTip: "Extremely common in meetings before starting a task.",
  },
  {
    id: "idm-0003",
    type: "Idiom",
    word: "cut corners",
    pronunciation: "/kʌt ˈkɔːrnərz/",
    partOfSpeech: "idiom",
    meaning: "to do something in the easiest or cheapest way, often sacrificing quality",
    hindiMeaning: "काम में कोताही बरतना",
    exampleSentence: "The contractor cut corners on materials, and the building suffered for it.",
    synonyms: ["skimp", "take shortcuts"],
    antonyms: ["do it properly", "go all out"],
    usageTip: "Usually has a negative connotation about compromising quality.",
  },
  {
    id: "idm-0004",
    type: "Idiom",
    word: "think outside the box",
    pronunciation: "/θɪŋk aʊtˈsaɪd ðə bɒks/",
    partOfSpeech: "idiom",
    meaning: "to think creatively, beyond conventional ideas",
    hindiMeaning: "अलग तरीके से सोचना",
    exampleSentence: "We need someone who can think outside the box to solve this problem.",
    synonyms: ["be creative", "innovate"],
    antonyms: ["think conventionally"],
    usageTip: "Very common in job ads and interviews about creativity.",
  },
  {
    id: "idm-0005",
    type: "Idiom",
    word: "back to square one",
    pronunciation: "/bæk tuː skwer wʌn/",
    partOfSpeech: "idiom",
    meaning: "to return to the starting point after a failed attempt",
    hindiMeaning: "फिर से शुरुआत करना",
    exampleSentence: "The deal fell through, so we're back to square one.",
    synonyms: ["start over", "back to the drawing board"],
    antonyms: ["move forward", "make progress"],
    usageTip: "Often used with a sigh of frustration in casual conversation.",
  },
  {
    id: "idm-0006",
    type: "Idiom",
    word: "burn the midnight oil",
    pronunciation: "/bɜːrn ðə ˈmɪdnaɪt ɔɪl/",
    partOfSpeech: "idiom",
    meaning: "to work late into the night",
    hindiMeaning: "देर रात तक काम करना",
    exampleSentence: "She's been burning the midnight oil to finish the thesis on time.",
    synonyms: ["work late", "pull an all-nighter"],
    antonyms: ["call it a day early"],
    usageTip: "Common when talking about deadlines and hard work.",
  },
  {
    id: "idm-0007",
    type: "Idiom",
    word: "call it a day",
    pronunciation: "/kɔːl ɪt ə deɪ/",
    partOfSpeech: "idiom",
    meaning: "to stop working on something for the rest of the day",
    hindiMeaning: "काम को यहीं समाप्त करना",
    exampleSentence: "We've made good progress — let's call it a day.",
    synonyms: ["wrap up", "finish for the day"],
    antonyms: ["keep going", "push on"],
    usageTip: "A friendly, casual way to end a work session.",
  },
  {
    id: "idm-0008",
    type: "Idiom",
    word: "get the ball rolling",
    pronunciation: "/ɡet ðə bɔːl ˈroʊlɪŋ/",
    partOfSpeech: "idiom",
    meaning: "to start a process or activity",
    hindiMeaning: "काम शुरू करना",
    exampleSentence: "Let's get the ball rolling on the new marketing campaign.",
    synonyms: ["kick things off", "initiate"],
    antonyms: ["stall", "delay"],
    usageTip: "Common opener in meetings: 'Let's get the ball rolling.'",
  },
  {
    id: "idm-0009",
    type: "Idiom",
    word: "under the weather",
    pronunciation: "/ˌʌndər ðə ˈweðər/",
    partOfSpeech: "idiom",
    meaning: "feeling slightly ill",
    hindiMeaning: "थोड़ा अस्वस्थ महसूस करना",
    exampleSentence: "I'm feeling a bit under the weather, so I might work from home today.",
    synonyms: ["unwell", "off-color"],
    antonyms: ["in great shape", "fit as a fiddle"],
    usageTip: "A polite, common way to say you're not feeling well without going into detail.",
  },
  {
    id: "idm-0010",
    type: "Idiom",
    word: "bite the bullet",
    pronunciation: "/baɪt ðə ˈbʊlɪt/",
    partOfSpeech: "idiom",
    meaning: "to force yourself to do something unpleasant or difficult",
    hindiMeaning: "कठिन परिस्थिति का सामना करना",
    exampleSentence: "I finally bit the bullet and had that difficult conversation with my boss.",
    synonyms: ["face up to it", "grit your teeth"],
    antonyms: ["avoid", "shy away from"],
    usageTip: "Great for describing a tough decision you finally made.",
  },
  {
    id: "idm-0011",
    type: "Idiom",
    word: "a piece of cake",
    pronunciation: "/ə piːs əv keɪk/",
    partOfSpeech: "idiom",
    meaning: "something very easy to do",
    hindiMeaning: "बहुत आसान काम",
    exampleSentence: "Don't worry about the test — it's a piece of cake.",
    synonyms: ["a walk in the park", "child's play"],
    antonyms: ["a tough nut to crack"],
    usageTip: "Very casual and commonly used in daily conversation.",
  },
  {
    id: "idm-0012",
    type: "Idiom",
    word: "beat around the bush",
    pronunciation: "/biːt əˈraʊnd ðə bʊʃ/",
    partOfSpeech: "idiom",
    meaning: "to avoid getting to the point of an issue",
    hindiMeaning: "घुमा-फिराकर बात करना",
    exampleSentence: "Stop beating around the bush and tell me what happened.",
    synonyms: ["stall", "avoid the point"],
    antonyms: ["get straight to the point"],
    usageTip: "Often used as a command: 'Don't beat around the bush.'",
  },
  {
    id: "idm-0013",
    type: "Idiom",
    word: "break the ice",
    pronunciation: "/breɪk ði aɪs/",
    partOfSpeech: "idiom",
    meaning: "to make people feel more relaxed in a social situation",
    hindiMeaning: "बातचीत की शुरुआत सहज बनाना",
    exampleSentence: "The host told a joke to break the ice before the interview began.",
    synonyms: ["ease the tension", "warm things up"],
    antonyms: ["create awkwardness"],
    usageTip: "'Icebreaker' is the noun form, often used for team activities.",
  },
  {
    id: "idm-0014",
    type: "Idiom",
    word: "in the loop",
    pronunciation: "/ɪn ðə luːp/",
    partOfSpeech: "idiom",
    meaning: "informed and included in decision-making or updates",
    hindiMeaning: "जानकारी में रखा जाना",
    exampleSentence: "Please keep me in the loop about any changes to the schedule.",
    synonyms: ["informed", "updated"],
    antonyms: ["out of the loop", "left in the dark"],
    usageTip: "Common in emails: 'keep me in the loop' or 'loop me in'.",
  },
  {
    id: "idm-0015",
    type: "Idiom",
    word: "go the extra mile",
    pronunciation: "/ɡoʊ ði ˈekstrə maɪl/",
    partOfSpeech: "idiom",
    meaning: "to make more effort than is expected",
    hindiMeaning: "अतिरिक्त प्रयास करना",
    exampleSentence: "Our support team always goes the extra mile for customers.",
    synonyms: ["go above and beyond", "put in extra effort"],
    antonyms: ["do the bare minimum"],
    usageTip: "A great interview phrase to describe dedication.",
  },
  {
    id: "idm-0016",
    type: "Idiom",
    word: "the tip of the iceberg",
    pronunciation: "/ðə tɪp əv ði ˈaɪsbɜːrɡ/",
    partOfSpeech: "idiom",
    meaning: "a small, visible part of a much larger problem",
    hindiMeaning: "बड़ी समस्या का एक छोटा हिस्सा",
    exampleSentence: "The layoffs are just the tip of the iceberg of the company's financial troubles.",
    synonyms: ["a small sign of something bigger"],
    antonyms: ["the whole picture"],
    usageTip: "Common in news reports about ongoing crises.",
  },
  {
    id: "idm-0017",
    type: "Idiom",
    word: "raining cats and dogs",
    pronunciation: "/ˈreɪnɪŋ kæts ənd dɒɡz/",
    partOfSpeech: "idiom",
    meaning: "raining very heavily",
    hindiMeaning: "मूसलाधार बारिश",
    exampleSentence: "We got soaked walking home — it was raining cats and dogs.",
    synonyms: ["pouring", "bucketing down"],
    antonyms: ["drizzling", "clear skies"],
    usageTip: "A classic weather idiom, useful for daily small talk.",
  },
  {
    id: "idm-0018",
    type: "Idiom",
    word: "spill the beans",
    pronunciation: "/spɪl ðə biːnz/",
    partOfSpeech: "idiom",
    meaning: "to reveal secret information",
    hindiMeaning: "राज़ खोलना",
    exampleSentence: "Come on, spill the beans — what happened at the meeting?",
    synonyms: ["let the cat out of the bag", "reveal a secret"],
    antonyms: ["keep it under wraps"],
    usageTip: "Casual and playful — often used among friends.",
  },
  {
    id: "idm-0019",
    type: "Idiom",
    word: "sit on the fence",
    pronunciation: "/sɪt ɒn ðə fens/",
    partOfSpeech: "idiom",
    meaning: "to avoid making a decision or taking sides",
    hindiMeaning: "निर्णय न लेना, तटस्थ रहना",
    exampleSentence: "He's still sitting on the fence about whether to accept the job offer.",
    synonyms: ["remain undecided", "stay neutral"],
    antonyms: ["take a stand", "commit"],
    usageTip: "Useful for expressing indecision in discussions.",
  },
  {
    id: "idm-0020",
    type: "Idiom",
    word: "once in a blue moon",
    pronunciation: "/wʌns ɪn ə bluː muːn/",
    partOfSpeech: "idiom",
    meaning: "very rarely",
    hindiMeaning: "कभी-कभार",
    exampleSentence: "We only eat out once in a blue moon these days.",
    synonyms: ["rarely", "hardly ever"],
    antonyms: ["frequently", "all the time"],
    usageTip: "Great for daily conversation about habits and frequency.",
  },
  {
    id: "idm-0021",
    type: "Idiom",
    word: "the ball is in your court",
    pronunciation: "/ðə bɔːl ɪz ɪn jʊər kɔːrt/",
    partOfSpeech: "idiom",
    meaning: "it's up to you to make the next decision",
    hindiMeaning: "अब निर्णय लेने की बारी आपकी है",
    exampleSentence: "I've sent the proposal — the ball is in your court now.",
    synonyms: ["it's your move", "the decision is yours"],
    antonyms: ["it's out of your hands"],
    usageTip: "Common in negotiations and business emails.",
  },
  {
    id: "idm-0022",
    type: "Idiom",
    word: "under the radar",
    pronunciation: "/ˌʌndər ðə ˈreɪdɑːr/",
    partOfSpeech: "idiom",
    meaning: "without attracting attention",
    hindiMeaning: "बिना ध्यान आकर्षित किए",
    exampleSentence: "The small startup grew quietly under the radar before its big launch.",
    synonyms: ["unnoticed", "under wraps"],
    antonyms: ["in the spotlight"],
    usageTip: "Frequently used in tech and business news.",
  },
  {
    id: "idm-0023",
    type: "Idiom",
    word: "food for thought",
    pronunciation: "/fuːd fər θɔːt/",
    partOfSpeech: "idiom",
    meaning: "something worth thinking about seriously",
    hindiMeaning: "सोचने लायक बात",
    exampleSentence: "That documentary really gave me food for thought about climate change.",
    synonyms: ["something to consider", "a point to ponder"],
    antonyms: ["irrelevant information"],
    usageTip: "Common after podcasts, talks, or thought-provoking discussions.",
  },
  {
    id: "idm-0024",
    type: "Idiom",
    word: "jump on the bandwagon",
    pronunciation: "/dʒʌmp ɒn ðə ˈbændwæɡən/",
    partOfSpeech: "idiom",
    meaning: "to join others in doing something popular",
    hindiMeaning: "किसी लोकप्रिय चीज़ में शामिल हो जाना",
    exampleSentence: "Many brands jumped on the bandwagon after the trend went viral.",
    synonyms: ["follow the crowd", "join the trend"],
    antonyms: ["go against the grain"],
    usageTip: "Common in marketing and social media discussions.",
  },
  {
    id: "idm-0025",
    type: "Idiom",
    word: "read between the lines",
    pronunciation: "/riːd bɪˈtwiːn ðə laɪnz/",
    partOfSpeech: "idiom",
    meaning: "to understand a hidden or implied meaning",
    hindiMeaning: "अंतर्निहित अर्थ समझना",
    exampleSentence: "If you read between the lines, you'll see he's actually unhappy with the deal.",
    synonyms: ["infer", "understand implicitly"],
    antonyms: ["take at face value"],
    usageTip: "Useful for describing subtle communication in feedback or emails.",
  },
  {
    id: "idm-0026",
    type: "Idiom",
    word: "keep your fingers crossed",
    pronunciation: "/kiːp jʊər ˈfɪŋɡərz krɒst/",
    partOfSpeech: "idiom",
    meaning: "to hope for a good outcome",
    hindiMeaning: "अच्छे परिणाम की उम्मीद करना",
    exampleSentence: "I'm keeping my fingers crossed for good news from the interview.",
    synonyms: ["hope for the best", "wish for luck"],
    antonyms: ["expect the worst"],
    usageTip: "Frequently used before exam results or interview outcomes.",
  },
  {
    id: "idm-0027",
    type: "Idiom",
    word: "wrap your head around",
    pronunciation: "/ræp jʊər hed əˈraʊnd/",
    partOfSpeech: "idiom",
    meaning: "to understand something complicated",
    hindiMeaning: "किसी जटिल बात को समझना",
    exampleSentence: "I'm still trying to wrap my head around the new tax policy.",
    synonyms: ["comprehend", "get your head around"],
    antonyms: ["be baffled by"],
    usageTip: "Common in casual conversations about confusing topics.",
  },
  {
    id: "idm-0028",
    type: "Idiom",
    word: "cost an arm and a leg",
    pronunciation: "/kɒst ən ɑːrm ənd ə leɡ/",
    partOfSpeech: "idiom",
    meaning: "to be very expensive",
    hindiMeaning: "बहुत महंगा होना",
    exampleSentence: "That designer bag cost an arm and a leg.",
    synonyms: ["cost a fortune", "break the bank"],
    antonyms: ["cost next to nothing"],
    usageTip: "Common in shopping and budgeting conversations.",
  },
  {
    id: "idm-0029",
    type: "Idiom",
    word: "a blessing in disguise",
    pronunciation: "/ə ˈblesɪŋ ɪn dɪsˈɡaɪz/",
    partOfSpeech: "idiom",
    meaning: "something that seems bad at first but turns out to be good",
    hindiMeaning: "छिपा हुआ वरदान",
    exampleSentence: "Losing that job was a blessing in disguise — it led me to my dream career.",
    synonyms: ["a hidden gift", "silver lining"],
    antonyms: ["a curse"],
    usageTip: "Great for storytelling in interviews about setbacks that led to growth.",
  },
  {
    id: "idm-0030",
    type: "Idiom",
    word: "put all your eggs in one basket",
    pronunciation: "/pʊt ɔːl jʊər eɡz ɪn wʌn ˈbɑːskɪt/",
    partOfSpeech: "idiom",
    meaning: "to risk everything on a single plan or option",
    hindiMeaning: "सारा दांव एक ही जगह लगाना",
    exampleSentence: "Don't put all your eggs in one basket — apply to multiple universities.",
    synonyms: ["risk it all on one thing"],
    antonyms: ["diversify", "spread the risk"],
    usageTip: "Common financial and career advice idiom.",
  },
  {
    id: "idm-0031",
    type: "Idiom",
    word: "when pigs fly",
    pronunciation: "/wen pɪɡz flaɪ/",
    partOfSpeech: "idiom",
    meaning: "something that will never happen",
    hindiMeaning: "कभी न होने वाली बात",
    exampleSentence: "He'll clean his room when pigs fly.",
    synonyms: ["never in a million years"],
    antonyms: ["definitely", "for sure"],
    usageTip: "Used sarcastically in casual, humorous conversation.",
  },
  {
    id: "idm-0032",
    type: "Idiom",
    word: "actions speak louder than words",
    pronunciation: "/ˈækʃənz spiːk ˈlaʊdər ðæn wɜːrdz/",
    partOfSpeech: "idiom",
    meaning: "what people do matters more than what they say",
    hindiMeaning: "कथनी से करनी बड़ी होती है",
    exampleSentence: "He promised to help, but actions speak louder than words.",
    synonyms: ["deeds over words"],
    antonyms: ["all talk, no action"],
    usageTip: "A common proverb used in leadership and motivational talks.",
  },
  {
    id: "idm-0033",
    type: "Idiom",
    word: "don't judge a book by its cover",
    pronunciation: "/doʊnt dʒʌdʒ ə bʊk baɪ ɪts ˈkʌvər/",
    partOfSpeech: "idiom",
    meaning: "don't form an opinion based only on appearance",
    hindiMeaning: "बाहरी रूप से किसी की परख न करें",
    exampleSentence: "He looked unapproachable, but don't judge a book by its cover — he's very kind.",
    synonyms: ["look beneath the surface"],
    antonyms: ["judge at first glance"],
    usageTip: "Widely used proverb in daily conversation about first impressions.",
  },
  {
    id: "idm-0034",
    type: "Idiom",
    word: "hang in there",
    pronunciation: "/hæŋ ɪn ðer/",
    partOfSpeech: "idiom",
    meaning: "to stay determined during a difficult situation",
    hindiMeaning: "धैर्य बनाए रखना",
    exampleSentence: "I know things are tough right now, but hang in there.",
    synonyms: ["stay strong", "don't give up"],
    antonyms: ["give up"],
    usageTip: "A warm, supportive phrase used to encourage someone.",
  },
  {
    id: "idm-0035",
    type: "Idiom",
    word: "throw in the towel",
    pronunciation: "/θroʊ ɪn ðə ˈtaʊəl/",
    partOfSpeech: "idiom",
    meaning: "to give up on something",
    hindiMeaning: "हार मान लेना",
    exampleSentence: "After three failed attempts, he finally threw in the towel.",
    synonyms: ["give up", "quit"],
    antonyms: ["persevere", "keep fighting"],
    usageTip: "Comes from boxing — used widely outside sports too.",
  },
  {
    id: "idm-0036",
    type: "Idiom",
    word: "see eye to eye",
    pronunciation: "/siː aɪ tuː aɪ/",
    partOfSpeech: "idiom",
    meaning: "to agree with someone",
    hindiMeaning: "एकमत होना",
    exampleSentence: "We don't always see eye to eye, but we respect each other's opinions.",
    synonyms: ["be in agreement", "share the same view"],
    antonyms: ["disagree", "clash"],
    usageTip: "Often used in negative form: 'we don't see eye to eye on this'.",
  },

  // ============================================================
  // PHRASAL VERBS (27 entries) — id prefix: pv-
  // ============================================================
  {
    id: "pv-0001",
    type: "Phrasal Verb",
    word: "bring up",
    pronunciation: "/brɪŋ ʌp/",
    partOfSpeech: "phrasal verb",
    meaning: "to mention or raise a topic",
    hindiMeaning: "किसी विषय का उल्लेख करना",
    exampleSentence: "She brought up the issue of remote work during the meeting.",
    synonyms: ["mention", "raise"],
    antonyms: ["avoid", "suppress"],
    usageTip: "Also means 'to raise a child' — context determines the meaning.",
  },
  {
    id: "pv-0002",
    type: "Phrasal Verb",
    word: "follow up",
    pronunciation: "/ˈfɒloʊ ʌp/",
    partOfSpeech: "phrasal verb",
    meaning: "to check on progress or continue an earlier action",
    hindiMeaning: "आगे की कार्रवाई करना",
    exampleSentence: "I'll follow up with the client tomorrow about the proposal.",
    synonyms: ["check back", "pursue"],
    antonyms: ["drop it", "let it go"],
    usageTip: "Extremely common in professional emails: 'Just following up on my last message.'",
  },
  {
    id: "pv-0003",
    type: "Phrasal Verb",
    word: "figure out",
    pronunciation: "/ˈfɪɡjər aʊt/",
    partOfSpeech: "phrasal verb",
    meaning: "to understand or solve something after thought",
    hindiMeaning: "समझना, हल निकालना",
    exampleSentence: "It took a while, but we finally figured out the bug in the code.",
    synonyms: ["work out", "resolve"],
    antonyms: ["remain confused"],
    usageTip: "One of the most common phrasal verbs in everyday spoken English.",
  },
  {
    id: "pv-0004",
    type: "Phrasal Verb",
    word: "carry out",
    pronunciation: "/ˈkæri aʊt/",
    partOfSpeech: "phrasal verb",
    meaning: "to perform or complete a task",
    hindiMeaning: "पूरा करना, संपन्न करना",
    exampleSentence: "The team carried out extensive research before launching the product.",
    synonyms: ["execute", "conduct"],
    antonyms: ["abandon", "neglect"],
    usageTip: "Very common in formal business and academic writing.",
  },
  {
    id: "pv-0005",
    type: "Phrasal Verb",
    word: "come up with",
    pronunciation: "/kʌm ʌp wɪð/",
    partOfSpeech: "phrasal verb",
    meaning: "to think of an idea or plan",
    hindiMeaning: "कोई विचार सोचना",
    exampleSentence: "The team came up with a brilliant marketing idea overnight.",
    synonyms: ["devise", "conceive"],
    antonyms: ["copy", "borrow"],
    usageTip: "Common in brainstorming sessions: 'Let's come up with some ideas.'",
  },
  {
    id: "pv-0006",
    type: "Phrasal Verb",
    word: "put off",
    pronunciation: "/pʊt ɒf/",
    partOfSpeech: "phrasal verb",
    meaning: "to postpone or delay",
    hindiMeaning: "टालना",
    exampleSentence: "We had to put off the launch because of technical issues.",
    synonyms: ["postpone", "delay"],
    antonyms: ["bring forward", "expedite"],
    usageTip: "Also means 'to make someone dislike something' — 'the smell put me off.'",
  },
  {
    id: "pv-0007",
    type: "Phrasal Verb",
    word: "point out",
    pronunciation: "/pɔɪnt aʊt/",
    partOfSpeech: "phrasal verb",
    meaning: "to draw attention to something",
    hindiMeaning: "ध्यान दिलाना, इशारा करना",
    exampleSentence: "My colleague pointed out an error in the spreadsheet.",
    synonyms: ["highlight", "indicate"],
    antonyms: ["overlook", "conceal"],
    usageTip: "Common in giving feedback: 'I'd like to point out one thing.'",
  },
  {
    id: "pv-0008",
    type: "Phrasal Verb",
    word: "set up",
    pronunciation: "/set ʌp/",
    partOfSpeech: "phrasal verb",
    meaning: "to establish or arrange something",
    hindiMeaning: "स्थापित करना, व्यवस्थित करना",
    exampleSentence: "We need to set up a meeting with the finance department.",
    synonyms: ["arrange", "establish"],
    antonyms: ["dismantle", "cancel"],
    usageTip: "Also used for technology: 'set up an account/device.'",
  },
  {
    id: "pv-0009",
    type: "Phrasal Verb",
    word: "look into",
    pronunciation: "/lʊk ˈɪntuː/",
    partOfSpeech: "phrasal verb",
    meaning: "to investigate or examine",
    hindiMeaning: "जांच करना",
    exampleSentence: "HR is looking into the complaint filed last week.",
    synonyms: ["investigate", "examine"],
    antonyms: ["ignore", "disregard"],
    usageTip: "A polite, professional way to say 'we will check this'.",
  },
  {
    id: "pv-0010",
    type: "Phrasal Verb",
    word: "back up",
    pronunciation: "/bæk ʌp/",
    partOfSpeech: "phrasal verb",
    meaning: "to support someone/something, or copy data for safety",
    hindiMeaning: "समर्थन करना; बैकअप लेना",
    exampleSentence: "Make sure to back up your files before updating the system.",
    synonyms: ["support", "safeguard"],
    antonyms: ["undermine", "delete"],
    usageTip: "Two meanings: emotional/verbal support, or technical data backup.",
  },
  {
    id: "pv-0011",
    type: "Phrasal Verb",
    word: "take on",
    pronunciation: "/teɪk ɒn/",
    partOfSpeech: "phrasal verb",
    meaning: "to accept responsibility or a challenge; to hire",
    hindiMeaning: "जिम्मेदारी लेना; नियुक्त करना",
    exampleSentence: "She decided to take on the new project despite her busy schedule.",
    synonyms: ["accept", "undertake"],
    antonyms: ["decline", "refuse"],
    usageTip: "Common in HR context: 'take on new staff'.",
  },
  {
    id: "pv-0012",
    type: "Phrasal Verb",
    word: "roll out",
    pronunciation: "/roʊl aʊt/",
    partOfSpeech: "phrasal verb",
    meaning: "to introduce a new product, policy, or service",
    hindiMeaning: "लॉन्च करना, शुरू करना",
    exampleSentence: "The company plans to roll out the new app next month.",
    synonyms: ["launch", "introduce"],
    antonyms: ["withdraw", "discontinue"],
    usageTip: "Very common in tech and business news: 'the rollout of a feature.'",
  },
  {
    id: "pv-0013",
    type: "Phrasal Verb",
    word: "iron out",
    pronunciation: "/ˈaɪərn aʊt/",
    partOfSpeech: "phrasal verb",
    meaning: "to resolve problems or difficulties through discussion",
    hindiMeaning: "समस्याओं को सुलझाना",
    exampleSentence: "We still need to iron out a few details before signing the contract.",
    synonyms: ["resolve", "sort out"],
    antonyms: ["complicate", "worsen"],
    usageTip: "Common in negotiations: 'iron out the differences'.",
  },
  {
    id: "pv-0014",
    type: "Phrasal Verb",
    word: "wind down",
    pronunciation: "/waɪnd daʊn/",
    partOfSpeech: "phrasal verb",
    meaning: "to relax after a period of work or stress; to gradually end",
    hindiMeaning: "आराम करना; धीरे-धीरे समाप्त करना",
    exampleSentence: "I like to wind down with a book before bed.",
    synonyms: ["relax", "unwind"],
    antonyms: ["gear up", "ramp up"],
    usageTip: "Also used for businesses closing down operations gradually.",
  },
  {
    id: "pv-0015",
    type: "Phrasal Verb",
    word: "touch base",
    pronunciation: "/tʌtʃ beɪs/",
    partOfSpeech: "phrasal verb",
    meaning: "to make brief contact or communication with someone",
    hindiMeaning: "संक्षिप्त संपर्क करना",
    exampleSentence: "Let's touch base next week to see how the project is going.",
    synonyms: ["check in", "connect briefly"],
    antonyms: ["lose touch"],
    usageTip: "Very common business email phrase: 'just touching base'.",
  },
  {
    id: "pv-0016",
    type: "Phrasal Verb",
    word: "weigh in",
    pronunciation: "/weɪ ɪn/",
    partOfSpeech: "phrasal verb",
    meaning: "to give an opinion on a discussion or debate",
    hindiMeaning: "अपनी राय देना",
    exampleSentence: "The CEO weighed in on the debate about remote work policies.",
    synonyms: ["contribute an opinion", "chime in"],
    antonyms: ["stay silent"],
    usageTip: "Common in panel discussions and news debates.",
  },
  {
    id: "pv-0017",
    type: "Phrasal Verb",
    word: "narrow down",
    pronunciation: "/ˈnæroʊ daʊn/",
    partOfSpeech: "phrasal verb",
    meaning: "to reduce the number of options",
    hindiMeaning: "विकल्पों को कम करना",
    exampleSentence: "We narrowed down the candidates to three finalists.",
    synonyms: ["shortlist", "reduce"],
    antonyms: ["expand", "broaden"],
    usageTip: "Common in hiring and decision-making contexts.",
  },
  {
    id: "pv-0018",
    type: "Phrasal Verb",
    word: "delve into",
    pronunciation: "/delv ˈɪntuː/",
    partOfSpeech: "phrasal verb",
    meaning: "to research or examine something thoroughly",
    hindiMeaning: "गहराई से जांच करना",
    exampleSentence: "The podcast delves into the psychology behind decision-making.",
    synonyms: ["explore deeply", "investigate"],
    antonyms: ["skim", "gloss over"],
    usageTip: "Common in podcasts, documentaries, and academic contexts.",
  },
  {
    id: "pv-0019",
    type: "Phrasal Verb",
    word: "opt out",
    pronunciation: "/ɒpt aʊt/",
    partOfSpeech: "phrasal verb",
    meaning: "to choose not to participate in something",
    hindiMeaning: "भाग न लेने का चुनाव करना",
    exampleSentence: "You can opt out of the newsletter anytime.",
    synonyms: ["withdraw", "decline participation"],
    antonyms: ["opt in", "sign up"],
    usageTip: "Common in subscription and legal/consent contexts.",
  },
  {
    id: "pv-0020",
    type: "Phrasal Verb",
    word: "bounce back",
    pronunciation: "/baʊns bæk/",
    partOfSpeech: "phrasal verb",
    meaning: "to recover quickly after a setback",
    hindiMeaning: "जल्दी उबरना",
    exampleSentence: "The economy bounced back faster than analysts expected.",
    synonyms: ["recover", "rebound"],
    antonyms: ["collapse", "decline further"],
    usageTip: "Common in interviews describing resilience after failure.",
  },
  {
    id: "pv-0021",
    type: "Phrasal Verb",
    word: "phase out",
    pronunciation: "/feɪz aʊt/",
    partOfSpeech: "phrasal verb",
    meaning: "to gradually stop using or providing something",
    hindiMeaning: "धीरे-धीरे समाप्त करना",
    exampleSentence: "The government plans to phase out single-use plastics by 2027.",
    synonyms: ["discontinue gradually", "wind down"],
    antonyms: ["phase in", "introduce"],
    usageTip: "Very common in BBC News environmental and policy stories.",
  },
  {
    id: "pv-0022",
    type: "Phrasal Verb",
    word: "map out",
    pronunciation: "/mæp aʊt/",
    partOfSpeech: "phrasal verb",
    meaning: "to plan something in detail",
    hindiMeaning: "विस्तार से योजना बनाना",
    exampleSentence: "Let's map out the entire project timeline before we begin.",
    synonyms: ["plan out", "outline"],
    antonyms: ["improvise"],
    usageTip: "Common in project management discussions.",
  },
  {
    id: "pv-0023",
    type: "Phrasal Verb",
    word: "single out",
    pronunciation: "/ˈsɪŋɡəl aʊt/",
    partOfSpeech: "phrasal verb",
    meaning: "to choose one person or thing from a group for special attention",
    hindiMeaning: "किसी एक को विशेष रूप से चुनना",
    exampleSentence: "The manager singled out two employees for their outstanding performance.",
    synonyms: ["highlight", "pick out"],
    antonyms: ["group together"],
    usageTip: "Can be positive (praise) or negative (unfair criticism) depending on context.",
  },
  {
    id: "pv-0024",
    type: "Phrasal Verb",
    word: "stem from",
    pronunciation: "/stem frʌm/",
    partOfSpeech: "phrasal verb",
    meaning: "to originate or result from something",
    hindiMeaning: "से उत्पन्न होना",
    exampleSentence: "The conflict stems from a miscommunication last month.",
    synonyms: ["originate from", "arise from"],
    antonyms: ["be unrelated to"],
    usageTip: "Common in analysis and reports discussing root causes.",
  },
  {
    id: "pv-0025",
    type: "Phrasal Verb",
    word: "chip in",
    pronunciation: "/tʃɪp ɪn/",
    partOfSpeech: "phrasal verb",
    meaning: "to contribute money, help, or ideas",
    hindiMeaning: "योगदान देना",
    exampleSentence: "Everyone chipped in to buy a farewell gift for our colleague.",
    synonyms: ["contribute", "pitch in"],
    antonyms: ["withhold"],
    usageTip: "Casual and friendly — common in office and social settings.",
  },
  {
    id: "pv-0026",
    type: "Phrasal Verb",
    word: "level up",
    pronunciation: "/ˈlevəl ʌp/",
    partOfSpeech: "phrasal verb",
    meaning: "to improve or advance to a better stage",
    hindiMeaning: "स्तर ऊँचा करना",
    exampleSentence: "This course will help you level up your public speaking skills.",
    synonyms: ["upgrade", "improve significantly"],
    antonyms: ["fall behind"],
    usageTip: "Originally gaming slang, now common in career and self-improvement talk.",
  },
  {
    id: "pv-0027",
    type: "Phrasal Verb",
    word: "hold off",
    pronunciation: "/hoʊld ɒf/",
    partOfSpeech: "phrasal verb",
    meaning: "to delay doing something",
    hindiMeaning: "रोकना, स्थगित करना",
    exampleSentence: "Let's hold off on the announcement until the deal is finalized.",
    synonyms: ["postpone", "wait"],
    antonyms: ["proceed immediately"],
    usageTip: "Common in cautious business decision-making: 'hold off on X until Y'.",
  },

  // ============================================================
  // EXPRESSIONS (18 entries) — id prefix: exp-
  // ============================================================
  {
    id: "exp-0001",
    type: "Expression",
    word: "to be honest",
    pronunciation: "/tuː biː ˈɒnɪst/",
    partOfSpeech: "expression",
    meaning: "used to introduce a frank or sincere opinion",
    hindiMeaning: "सच कहूँ तो",
    exampleSentence: "To be honest, I don't think we're ready to launch yet.",
    synonyms: ["frankly", "honestly speaking"],
    antonyms: ["to be evasive"],
    usageTip: "A natural filler to soften direct opinions in conversation.",
  },
  {
    id: "exp-0002",
    type: "Expression",
    word: "at the end of the day",
    pronunciation: "/æt ði end əv ðə deɪ/",
    partOfSpeech: "expression",
    meaning: "used to summarize the most important point after considering everything",
    hindiMeaning: "आखिरकार, कुल मिलाकर",
    exampleSentence: "At the end of the day, customer satisfaction is what matters most.",
    synonyms: ["ultimately", "when all is said and done"],
    antonyms: ["initially"],
    usageTip: "Very common in business discussions to conclude a point.",
  },
  {
    id: "exp-0003",
    type: "Expression",
    word: "for what it's worth",
    pronunciation: "/fɔːr wɒt ɪts wɜːrθ/",
    partOfSpeech: "expression",
    meaning: "used to share an opinion humbly, acknowledging it may not carry much weight",
    hindiMeaning: "जो भी हो, मेरी राय में",
    exampleSentence: "For what it's worth, I think your idea has real potential.",
    synonyms: ["in my opinion", "for what it matters"],
    antonyms: ["definitively"],
    usageTip: "A humble way to offer feedback or opinion in a discussion.",
  },
  {
    id: "exp-0004",
    type: "Expression",
    word: "long story short",
    pronunciation: "/lɒŋ ˈstɔːri ʃɔːrt/",
    partOfSpeech: "expression",
    meaning: "used to summarize a longer explanation briefly",
    hindiMeaning: "संक्षेप में कहें तो",
    exampleSentence: "Long story short, we missed the flight and had to rebook everything.",
    synonyms: ["in short", "to sum up"],
    antonyms: ["in full detail"],
    usageTip: "Perfect for casual storytelling when you want to skip details.",
  },
  {
    id: "exp-0005",
    type: "Expression",
    word: "if I'm being honest",
    pronunciation: "/ɪf aɪm ˈbiːɪŋ ˈɒnɪst/",
    partOfSpeech: "expression",
    meaning: "used before a sincere or blunt statement",
    hindiMeaning: "अगर सच कहूं तो",
    exampleSentence: "If I'm being honest, I wasn't fully prepared for the interview.",
    synonyms: ["to be frank", "honestly"],
    antonyms: ["to put it mildly"],
    usageTip: "Common in interviews when giving a candid self-assessment.",
  },
  {
    id: "exp-0006",
    type: "Expression",
    word: "that being said",
    pronunciation: "/ðæt ˈbiːɪŋ sed/",
    partOfSpeech: "expression",
    meaning: "used to introduce a contrasting point after acknowledging something",
    hindiMeaning: "फिर भी, ऐसा कहने के बावजूद",
    exampleSentence: "The results were disappointing. That being said, we learned a lot.",
    synonyms: ["however", "nevertheless"],
    antonyms: ["consequently"],
    usageTip: "A sophisticated transition phrase — great for IELTS speaking coherence.",
  },
  {
    id: "exp-0007",
    type: "Expression",
    word: "it is what it is",
    pronunciation: "/ɪt ɪz wɒt ɪt ɪz/",
    partOfSpeech: "expression",
    meaning: "used to accept a difficult situation that cannot be changed",
    hindiMeaning: "जो है सो है",
    exampleSentence: "We lost the client, but it is what it is — let's move forward.",
    synonyms: ["que sera sera", "such is life"],
    antonyms: ["we can still fix it"],
    usageTip: "Common in casual conversation to express calm acceptance.",
  },
  {
    id: "exp-0008",
    type: "Expression",
    word: "no offense, but",
    pronunciation: "/noʊ əˈfens bʌt/",
    partOfSpeech: "expression",
    meaning: "used before saying something that might sound critical",
    hindiMeaning: "बुरा मत मानना, लेकिन",
    exampleSentence: "No offense, but I think we should reconsider this plan.",
    synonyms: ["with respect", "not to be rude, but"],
    antonyms: ["I mean this as a compliment"],
    usageTip: "Softens criticism, though overuse can sound insincere.",
  },
  {
    id: "exp-0009",
    type: "Expression",
    word: "correct me if I'm wrong",
    pronunciation: "/kəˈrekt miː ɪf aɪm rɒŋ/",
    partOfSpeech: "expression",
    meaning: "used before stating something you're not fully certain about",
    hindiMeaning: "अगर मैं गलत हूं तो सुधार दें",
    exampleSentence: "Correct me if I'm wrong, but didn't we agree on a different deadline?",
    synonyms: ["if I understand correctly"],
    antonyms: ["I'm absolutely certain that"],
    usageTip: "A polite way to challenge or clarify a point in meetings.",
  },
  {
    id: "exp-0010",
    type: "Expression",
    word: "the thing is",
    pronunciation: "/ðə θɪŋ ɪz/",
    partOfSpeech: "expression",
    meaning: "used to introduce the main point or a problem",
    hindiMeaning: "असल बात यह है",
    exampleSentence: "The thing is, we don't have the budget for that right now.",
    synonyms: ["the issue is", "here's the problem"],
    antonyms: ["irrelevantly"],
    usageTip: "Very natural spoken filler for introducing a key point.",
  },
  {
    id: "exp-0011",
    type: "Expression",
    word: "at the end of the road",
    pronunciation: "/æt ði end əv ðə roʊd/",
    partOfSpeech: "expression",
    meaning: "reaching the final point of a process or effort, often with no further options",
    hindiMeaning: "अंतिम पड़ाव पर पहुंचना",
    exampleSentence: "After years of trying, they felt they were at the end of the road with the business.",
    synonyms: ["at a dead end", "out of options"],
    antonyms: ["at the starting line"],
    usageTip: "Often used for difficult or final decisions.",
  },
  {
    id: "exp-0012",
    type: "Expression",
    word: "easier said than done",
    pronunciation: "/ˈiːziər sed ðæn dʌn/",
    partOfSpeech: "expression",
    meaning: "used to say something sounds simple in theory but is hard in practice",
    hindiMeaning: "कहना आसान, करना मुश्किल",
    exampleSentence: "Losing weight sounds simple, but it's easier said than done.",
    synonyms: ["not as simple as it sounds"],
    antonyms: ["a piece of cake"],
    usageTip: "Common response to advice that oversimplifies a challenge.",
  },
  {
    id: "exp-0013",
    type: "Expression",
    word: "you can say that again",
    pronunciation: "/juː kæn seɪ ðæt əˈɡen/",
    partOfSpeech: "expression",
    meaning: "used to strongly agree with what someone said",
    hindiMeaning: "बिल्कुल सही कहा",
    exampleSentence: "\"That meeting went on forever.\" \"You can say that again!\"",
    synonyms: ["I couldn't agree more", "exactly"],
    antonyms: ["I disagree completely"],
    usageTip: "Informal expression of strong agreement in casual talk.",
  },
  {
    id: "exp-0014",
    type: "Expression",
    word: "let's circle back",
    pronunciation: "/lets ˈsɜːrkəl bæk/",
    partOfSpeech: "expression",
    meaning: "used to suggest returning to a topic later",
    hindiMeaning: "बाद में इस पर फिर से चर्चा करें",
    exampleSentence: "Let's circle back to the budget discussion after lunch.",
    synonyms: ["let's revisit", "let's come back to this"],
    antonyms: ["let's finalize this now"],
    usageTip: "Common corporate jargon in meetings — useful but can sound cliché if overused.",
  },
  {
    id: "exp-0015",
    type: "Expression",
    word: "at your earliest convenience",
    pronunciation: "/æt jʊər ˈɜːrliɪst kənˈviːniəns/",
    partOfSpeech: "expression",
    meaning: "as soon as reasonably possible",
    hindiMeaning: "जितनी जल्दी हो सके",
    exampleSentence: "Please send the documents at your earliest convenience.",
    synonyms: ["as soon as possible", "when you get a chance"],
    antonyms: ["whenever, no rush"],
    usageTip: "A formal, polite phrase common in professional emails.",
  },
  {
    id: "exp-0016",
    type: "Expression",
    word: "with all due respect",
    pronunciation: "/wɪð ɔːl djuː rɪˈspekt/",
    partOfSpeech: "expression",
    meaning: "used to politely disagree with someone, especially someone senior",
    hindiMeaning: "सम्मान सहित, लेकिन",
    exampleSentence: "With all due respect, I think we should consider a different vendor.",
    synonyms: ["respectfully", "with respect"],
    antonyms: ["bluntly"],
    usageTip: "Useful for disagreeing politely with a superior in formal settings.",
  },
  {
    id: "exp-0017",
    type: "Expression",
    word: "practice what you preach",
    pronunciation: "/ˈpræktɪs wɒt juː priːtʃ/",
    partOfSpeech: "expression",
    meaning: "to act in accordance with what you advise others to do",
    hindiMeaning: "जो कहो वही करो",
    exampleSentence: "As a leader, you have to practice what you preach.",
    synonyms: ["lead by example", "walk the talk"],
    antonyms: ["be a hypocrite"],
    usageTip: "Common in leadership and integrity-focused conversations.",
  },
  {
    id: "exp-0018",
    type: "Expression",
    word: "food for the soul",
    pronunciation: "/fuːd fər ðə soʊl/",
    partOfSpeech: "expression",
    meaning: "something that brings deep emotional or spiritual satisfaction",
    hindiMeaning: "आत्मा को सुकून देने वाला",
    exampleSentence: "Listening to live music after a long week is food for the soul.",
    synonyms: ["deeply nourishing", "uplifting"],
    antonyms: ["draining", "empty"],
    usageTip: "A poetic expression often used in casual, reflective conversation.",
  },

  // ============================================================
  // COLLOCATIONS (9 entries) — id prefix: col-
  // ============================================================
  {
    id: "col-0001",
    type: "Collocation",
    word: "make a decision",
    pronunciation: "/meɪk ə dɪˈsɪʒən/",
    partOfSpeech: "collocation (verb + noun)",
    meaning: "to decide on something",
    hindiMeaning: "निर्णय लेना",
    exampleSentence: "We need to make a decision by the end of the week.",
    synonyms: ["reach a decision", "come to a conclusion"],
    antonyms: ["remain undecided"],
    usageTip: "Use 'make', not 'take' — a very common collocation error for learners.",
  },
  {
    id: "col-0002",
    type: "Collocation",
    word: "reach a consensus",
    pronunciation: "/riːtʃ ə kənˈsensəs/",
    partOfSpeech: "collocation (verb + noun)",
    meaning: "to come to a general agreement among a group",
    hindiMeaning: "सर्वसम्मति पर पहुंचना",
    exampleSentence: "It took two long meetings to reach a consensus on the budget.",
    synonyms: ["reach an agreement", "come to terms"],
    antonyms: ["remain divided"],
    usageTip: "Common in formal meetings and negotiations.",
  },
  {
    id: "col-0003",
    type: "Collocation",
    word: "pay attention",
    pronunciation: "/peɪ əˈtenʃən/",
    partOfSpeech: "collocation (verb + noun)",
    meaning: "to focus on or concentrate on something",
    hindiMeaning: "ध्यान देना",
    exampleSentence: "Please pay attention to the instructions before starting the task.",
    synonyms: ["focus on", "concentrate on"],
    antonyms: ["ignore", "disregard"],
    usageTip: "'Pay' is the correct verb here — 'give attention' sounds unnatural.",
  },
  {
    id: "col-0004",
    type: "Collocation",
    word: "take responsibility",
    pronunciation: "/teɪk rɪˌspɒnsəˈbɪləti/",
    partOfSpeech: "collocation (verb + noun)",
    meaning: "to accept accountability for something",
    hindiMeaning: "जिम्मेदारी लेना",
    exampleSentence: "A good leader takes responsibility for the team's mistakes too.",
    synonyms: ["accept accountability", "own up to"],
    antonyms: ["shift the blame"],
    usageTip: "Common interview phrase: 'I take full responsibility for...'.",
  },
  {
    id: "col-0005",
    type: "Collocation",
    word: "raise awareness",
    pronunciation: "/reɪz əˈwernəs/",
    partOfSpeech: "collocation (verb + noun)",
    meaning: "to help people know more about an important issue",
    hindiMeaning: "जागरूकता बढ़ाना",
    exampleSentence: "The campaign aims to raise awareness about mental health.",
    synonyms: ["spread awareness", "educate the public"],
    antonyms: ["suppress information"],
    usageTip: "Very common in NGO, healthcare, and TED Talk contexts.",
  },
  {
    id: "col-0006",
    type: "Collocation",
    word: "strike a balance",
    pronunciation: "/straɪk ə ˈbæləns/",
    partOfSpeech: "collocation (verb + noun)",
    meaning: "to find a satisfactory middle point between two extremes",
    hindiMeaning: "संतुलन बनाना",
    exampleSentence: "It's important to strike a balance between work and personal life.",
    synonyms: ["find a balance", "achieve equilibrium"],
    antonyms: ["tip the scale"],
    usageTip: "A popular IELTS phrase for discussing work-life balance topics.",
  },
  {
    id: "col-0007",
    type: "Collocation",
    word: "meet a deadline",
    pronunciation: "/miːt ə ˈdedlaɪn/",
    partOfSpeech: "collocation (verb + noun)",
    meaning: "to complete something by the required time",
    hindiMeaning: "समय सीमा पूरी करना",
    exampleSentence: "The whole team worked overtime to meet the deadline.",
    synonyms: ["hit the deadline", "deliver on time"],
    antonyms: ["miss the deadline"],
    usageTip: "Common workplace phrase — the opposite, 'miss a deadline', is equally useful.",
  },
  {
    id: "col-0008",
    type: "Collocation",
    word: "draw a conclusion",
    pronunciation: "/drɔː ə kənˈkluːʒən/",
    partOfSpeech: "collocation (verb + noun)",
    meaning: "to decide something is true after considering the facts",
    hindiMeaning: "निष्कर्ष निकालना",
    exampleSentence: "It's too early to draw a conclusion from such limited data.",
    synonyms: ["come to a conclusion", "infer"],
    antonyms: ["remain uncertain"],
    usageTip: "Common in academic and research-based English.",
  },
  {
    id: "col-0009",
    type: "Collocation",
    word: "gain momentum",
    pronunciation: "/ɡeɪn moʊˈmentəm/",
    partOfSpeech: "collocation (verb + noun)",
    meaning: "to develop increasing speed, force, or popularity",
    hindiMeaning: "गति पकड़ना",
    exampleSentence: "The campaign gained momentum after going viral online.",
    synonyms: ["build momentum", "pick up speed"],
    antonyms: ["lose momentum", "stall"],
    usageTip: "Common in business and news reports about trends and movements.",
  },
];

// ------------------------------------------------------------------
// Quick composition summary (for reference — not used at runtime):
//   Words:           90  (50%)
//   Idioms:          36  (20%)
//   Phrasal Verbs:   27  (15%)
//   Expressions:     18  (10%)
//   Collocations:     9   (5%)
//   TOTAL:          180 entries, all unique, no repeats.
// ------------------------------------------------------------------
